[tools]
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.28.0"
stylua = "JohnnyMorganz/StyLua@2.0.2"
lune = "lune-org/lune@0.9.4"
# rbxcloud available globally via cargo if needed for Open Cloud APIs
